name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcunit1-dev
    - name: Test
      run: make test
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: ./test-results.xml
      
