name: C/C++ CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cache CUnit
      uses: actions/cache@v3
      with:
        path: ~/cunit
        key: ${{ runner.os }}-cunit-${{ hashFiles('**/Makefile') }}

    - name: Install dependencies
      run: |
        if [ ! -d "~/cunit" ]; then
          sudo apt-get install -y libcunit1-dev
        fi
        
    - name: Test
      run: make test 2>&1 | tee test-output.txt
      
    - name: Upload Test Output
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TestOutput
        path: ./test-output.txt
      
